# Form implementation generated from reading ui file 'd:\JohnHu\Github_private\ESP32_S3_WROOM_1\code\AI_Profile\main\user\pyqt\qt6\total.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 860)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #050b14;\n"
"}\n"
"QTabWidget::pane {\n"
"    border: 1px solid #0b2236;\n"
"    top: -1px;\n"
"    background-color: #050b14;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: #0b1728;\n"
"    color: #9ab8d3;\n"
"    border: 1px solid #12314d;\n"
"    border-bottom-color: #0b2236;\n"
"    padding: 6px 14px;\n"
"    margin-right: 2px;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color: #0f2238;\n"
"    color: #e1f1ff;\n"
"    border-color: #1b4a72;\n"
"}\n"
"QTabBar::tab:hover:!selected {\n"
"    background-color: #112840;\n"
"    color: #cce6ff;\n"
"}\n"
"QWidget#steering_tab {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #050c17, stop:0.55 #071428, stop:1 #040912);\n"
"}\n"
"QWidget#steering_tab QLabel {\n"
"    color: #afc1d4;\n"
"    font-family: Bahnschrift;\n"
"    font-size: 10pt;\n"
"}\n"
"QWidget#steering_tab QFrame#steering_hero_card {\n"
"    border: 1px solid #10314b;\n"
"    border-radius: 12px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #10263f, stop:1 #0a1728);\n"
"}\n"
"QWidget#steering_tab QLabel#steering_hero_title {\n"
"    color: #63e6ff;\n"
"    font-size: 14pt;\n"
"    font-weight: 700;\n"
"    letter-spacing: 1px;\n"
"}\n"
"QWidget#steering_tab QLabel#steering_hero_subtitle {\n"
"    color: #8fb1cf;\n"
"}\n"
"QWidget#steering_tab QFrame#scope_card,\n"
"QWidget#steering_tab QFrame#pid_card,\n"
"QWidget#steering_tab QFrame#setpoint_card,\n"
"QWidget#steering_tab QFrame#runtime_card {\n"
"    border: 1px solid #0f2b44;\n"
"    border-radius: 11px;\n"
"    background-color: #081427;\n"
"}\n"
"QWidget#steering_tab QLabel#scope_title,\n"
"QWidget#steering_tab QLabel#pid_title,\n"
"QWidget#steering_tab QLabel#setpoint_title,\n"
"QWidget#steering_tab QLabel#runtime_title,\n"
"QWidget#steering_tab QLabel#telemetry_raw_title {\n"
"    color: #57dbff;\n"
"    font-size: 11pt;\n"
"    font-weight: 700;\n"
"    letter-spacing: 1px;\n"
"}\n"
"QWidget#steering_tab QLabel#scope_hint,\n"
"QWidget#steering_tab QLabel#runtime_hint,\n"
"QWidget#steering_tab QLabel#setpoint_hint {\n"
"    color: #7d97af;\n"
"}\n"
"QWidget#steering_tab QLabel#scope_live_badge {\n"
"    color: #7fffcf;\n"
"    border: 1px solid #20543f;\n"
"    border-radius: 7px;\n"
"    background-color: #0a3025;\n"
"    padding: 2px 8px;\n"
"    font-weight: 700;\n"
"}\n"
"QWidget#steering_tab QLabel#steering_conn_led {\n"
"    background-color: #090909;\n"
"    border: 1px solid #2a3644;\n"
"    border-radius: 12px;\n"
"}\n"
"QWidget#steering_tab QFrame#scope_host {\n"
"    border: 1px solid #1a3a55;\n"
"    border-radius: 8px;\n"
"    background-color: #040b16;\n"
"}\n"
"QWidget#steering_tab QPlainTextEdit#telemetry_raw_view {\n"
"    border: 1px solid #1e425f;\n"
"    border-radius: 8px;\n"
"    background-color: #030913;\n"
"    color: #9fe7c0;\n"
"    selection-background-color: #184e73;\n"
"    font-family: Consolas;\n"
"    font-size: 10pt;\n"
"}\n"
"QWidget#steering_tab QPushButton {\n"
"    border: 1px solid #20506f;\n"
"    border-radius: 7px;\n"
"    background-color: #0d2136;\n"
"    color: #d2e6fb;\n"
"    min-height: 28px;\n"
"    padding: 2px 10px;\n"
"}\n"
"QWidget#steering_tab QPushButton:hover {\n"
"    border-color: #2f88be;\n"
"    background-color: #12304b;\n"
"}\n"
"QWidget#steering_tab QPushButton:pressed {\n"
"    background-color: #153a5d;\n"
"}\n"
"QWidget#steering_tab QPushButton:disabled {\n"
"    color: #5f7285;\n"
"    border-color: #213246;\n"
"    background-color: #0a1624;\n"
"}\n"
"QWidget#steering_tab QPushButton#setpoint_send_button,\n"
"QWidget#steering_tab QPushButton#pid_apply_button,\n"
"QWidget#steering_tab QPushButton#motor_enable_button,\n"
"QWidget#steering_tab QPushButton#telemetry_send_button {\n"
"    border-color: #2b8fbe;\n"
"    color: #73ebff;\n"
"    background-color: #10344f;\n"
"}\n"
"QWidget#steering_tab QPushButton#motor_stop_button {\n"
"    border-color: #a65262;\n"
"    color: #ffc0cb;\n"
"    background-color: #311723;\n"
"}\n"
"QWidget#steering_tab QDoubleSpinBox,\n"
"QWidget#steering_tab QComboBox,\n"
"QWidget#steering_tab QLineEdit {\n"
"    border: 1px solid #1f4f74;\n"
"    border-radius: 7px;\n"
"    background-color: #061021;\n"
"    color: #b9d6ef;\n"
"    min-height: 26px;\n"
"    padding: 2px 8px;\n"
"    font-family: Consolas;\n"
"}\n"
"QWidget#steering_tab QDoubleSpinBox:focus,\n"
"QWidget#steering_tab QComboBox:focus,\n"
"QWidget#steering_tab QLineEdit:focus {\n"
"    border-color: #46d4ff;\n"
"}\n"
"QWidget#steering_tab QDial#angle_knob {\n"
"    background-color: #07182d;\n"
"    border: 1px solid #1a4366;\n"
"    border-radius: 68px;\n"
"}\n"
"QWidget#steering_tab QLabel#knob_value_lab,\n"
"QWidget#steering_tab QLabel#rt_conn_value,\n"
"QWidget#steering_tab QLabel#rt_set_value,\n"
"QWidget#steering_tab QLabel#rt_fb_value,\n"
"QWidget#steering_tab QLabel#rt_err_value,\n"
"QWidget#steering_tab QLabel#rt_pwm_value,\n"
"QWidget#steering_tab QLabel#rt_rpm_value,\n"
"QWidget#steering_tab QLabel#rt_vbus_value {\n"
"    color: #7af0ff;\n"
"    font-weight: 700;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.ble_tab = QtWidgets.QWidget()
        self.ble_tab.setObjectName("ble_tab")
        self.ble_root_layout = QtWidgets.QVBoxLayout(self.ble_tab)
        self.ble_root_layout.setContentsMargins(12, 12, 12, 12)
        self.ble_root_layout.setSpacing(10)
        self.ble_root_layout.setObjectName("ble_root_layout")
        self.hero_card = QtWidgets.QFrame(parent=self.ble_tab)
        self.hero_card.setObjectName("hero_card")
        self.hero_layout = QtWidgets.QVBoxLayout(self.hero_card)
        self.hero_layout.setContentsMargins(14, 10, 14, 10)
        self.hero_layout.setSpacing(2)
        self.hero_layout.setObjectName("hero_layout")
        self.hero_title_row = QtWidgets.QHBoxLayout()
        self.hero_title_row.setSpacing(8)
        self.hero_title_row.setObjectName("hero_title_row")
        self.hero_title = QtWidgets.QLabel(parent=self.hero_card)
        self.hero_title.setObjectName("hero_title")
        self.hero_title_row.addWidget(self.hero_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hero_title_row.addItem(spacerItem)
        self.ble_conn_led = QtWidgets.QLabel(parent=self.hero_card)
        self.ble_conn_led.setMinimumSize(QtCore.QSize(28, 28))
        self.ble_conn_led.setMaximumSize(QtCore.QSize(28, 28))
        self.ble_conn_led.setStyleSheet("QLabel#ble_conn_led {\n"
"    background-color: #090909;\n"
"    border: 1px solid #2a3644;\n"
"    border-radius: 14px;\n"
"}")
        self.ble_conn_led.setText("")
        self.ble_conn_led.setObjectName("ble_conn_led")
        self.hero_title_row.addWidget(self.ble_conn_led)
        self.hero_layout.addLayout(self.hero_title_row)
        self.hero_subtitle = QtWidgets.QLabel(parent=self.hero_card)
        self.hero_subtitle.setObjectName("hero_subtitle")
        self.hero_layout.addWidget(self.hero_subtitle)
        self.ble_root_layout.addWidget(self.hero_card)
        self.control_card = QtWidgets.QFrame(parent=self.ble_tab)
        self.control_card.setObjectName("control_card")
        self.control_layout = QtWidgets.QVBoxLayout(self.control_card)
        self.control_layout.setContentsMargins(12, 10, 12, 10)
        self.control_layout.setSpacing(8)
        self.control_layout.setObjectName("control_layout")
        self.section_title = QtWidgets.QLabel(parent=self.control_card)
        self.section_title.setObjectName("section_title")
        self.control_layout.addWidget(self.section_title)
        self.control_grid = QtWidgets.QGridLayout()
        self.control_grid.setSpacing(8)
        self.control_grid.setObjectName("control_grid")
        self.device_filter_lab = QtWidgets.QLabel(parent=self.control_card)
        self.device_filter_lab.setObjectName("device_filter_lab")
        self.control_grid.addWidget(self.device_filter_lab, 0, 0, 1, 1)
        self.device_filter_edit = QtWidgets.QLineEdit(parent=self.control_card)
        self.device_filter_edit.setObjectName("device_filter_edit")
        self.control_grid.addWidget(self.device_filter_edit, 0, 1, 1, 3)
        self.action_row = QtWidgets.QHBoxLayout()
        self.action_row.setSpacing(8)
        self.action_row.setObjectName("action_row")
        self.scan_button = QtWidgets.QPushButton(parent=self.control_card)
        self.scan_button.setMinimumSize(QtCore.QSize(150, 0))
        self.scan_button.setMaximumSize(QtCore.QSize(150, 16777215))
        self.scan_button.setObjectName("scan_button")
        self.action_row.addWidget(self.scan_button)
        self.connect_button = QtWidgets.QPushButton(parent=self.control_card)
        self.connect_button.setMinimumSize(QtCore.QSize(120, 0))
        self.connect_button.setMaximumSize(QtCore.QSize(120, 16777215))
        self.connect_button.setObjectName("connect_button")
        self.action_row.addWidget(self.connect_button)
        self.disconnect_button = QtWidgets.QPushButton(parent=self.control_card)
        self.disconnect_button.setMinimumSize(QtCore.QSize(140, 0))
        self.disconnect_button.setMaximumSize(QtCore.QSize(140, 16777215))
        self.disconnect_button.setObjectName("disconnect_button")
        self.action_row.addWidget(self.disconnect_button)
        self.apply_config_button = QtWidgets.QPushButton(parent=self.control_card)
        self.apply_config_button.setMinimumSize(QtCore.QSize(170, 0))
        self.apply_config_button.setMaximumSize(QtCore.QSize(170, 16777215))
        self.apply_config_button.setObjectName("apply_config_button")
        self.action_row.addWidget(self.apply_config_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.action_row.addItem(spacerItem1)
        self.control_grid.addLayout(self.action_row, 0, 4, 1, 3)
        self.service_uuid_lab = QtWidgets.QLabel(parent=self.control_card)
        self.service_uuid_lab.setObjectName("service_uuid_lab")
        self.control_grid.addWidget(self.service_uuid_lab, 1, 0, 1, 1)
        self.service_uuid_edit = QtWidgets.QLineEdit(parent=self.control_card)
        self.service_uuid_edit.setObjectName("service_uuid_edit")
        self.control_grid.addWidget(self.service_uuid_edit, 1, 1, 1, 2)
        self.rx_uuid_lab = QtWidgets.QLabel(parent=self.control_card)
        self.rx_uuid_lab.setObjectName("rx_uuid_lab")
        self.control_grid.addWidget(self.rx_uuid_lab, 1, 3, 1, 1)
        self.rx_uuid_edit = QtWidgets.QLineEdit(parent=self.control_card)
        self.rx_uuid_edit.setObjectName("rx_uuid_edit")
        self.control_grid.addWidget(self.rx_uuid_edit, 1, 4, 1, 1)
        self.tx_uuid_lab = QtWidgets.QLabel(parent=self.control_card)
        self.tx_uuid_lab.setObjectName("tx_uuid_lab")
        self.control_grid.addWidget(self.tx_uuid_lab, 1, 5, 1, 1)
        self.tx_uuid_edit = QtWidgets.QLineEdit(parent=self.control_card)
        self.tx_uuid_edit.setObjectName("tx_uuid_edit")
        self.control_grid.addWidget(self.tx_uuid_edit, 1, 6, 1, 1)
        self.config_row = QtWidgets.QHBoxLayout()
        self.config_row.setObjectName("config_row")
        self.control_grid.addLayout(self.config_row, 2, 4, 1, 3)
        self.control_layout.addLayout(self.control_grid)
        self.ble_root_layout.addWidget(self.control_card)
        self.status_strip = QtWidgets.QFrame(parent=self.ble_tab)
        self.status_strip.setObjectName("status_strip")
        self.status_layout = QtWidgets.QVBoxLayout(self.status_strip)
        self.status_layout.setContentsMargins(12, 8, 12, 8)
        self.status_layout.setSpacing(6)
        self.status_layout.setObjectName("status_layout")
        self.chips_row = QtWidgets.QHBoxLayout()
        self.chips_row.setSpacing(8)
        self.chips_row.setObjectName("chips_row")
        self.chip_state = QtWidgets.QFrame(parent=self.status_strip)
        self.chip_state.setObjectName("chip_state")
        self.chip_state_layout = QtWidgets.QHBoxLayout(self.chip_state)
        self.chip_state_layout.setContentsMargins(8, 4, 8, 4)
        self.chip_state_layout.setSpacing(6)
        self.chip_state_layout.setObjectName("chip_state_layout")
        self.chip_key_state = QtWidgets.QLabel(parent=self.chip_state)
        self.chip_key_state.setObjectName("chip_key_state")
        self.chip_state_layout.addWidget(self.chip_key_state)
        self.conn_value = QtWidgets.QLabel(parent=self.chip_state)
        self.conn_value.setObjectName("conn_value")
        self.chip_state_layout.addWidget(self.conn_value)
        self.chips_row.addWidget(self.chip_state)
        self.chip_device = QtWidgets.QFrame(parent=self.status_strip)
        self.chip_device.setObjectName("chip_device")
        self.chip_device_layout = QtWidgets.QHBoxLayout(self.chip_device)
        self.chip_device_layout.setContentsMargins(8, 4, 8, 4)
        self.chip_device_layout.setSpacing(6)
        self.chip_device_layout.setObjectName("chip_device_layout")
        self.chip_key_device = QtWidgets.QLabel(parent=self.chip_device)
        self.chip_key_device.setObjectName("chip_key_device")
        self.chip_device_layout.addWidget(self.chip_key_device)
        self.device_value = QtWidgets.QLabel(parent=self.chip_device)
        self.device_value.setObjectName("device_value")
        self.chip_device_layout.addWidget(self.device_value)
        self.chips_row.addWidget(self.chip_device)
        self.chip_service = QtWidgets.QFrame(parent=self.status_strip)
        self.chip_service.setObjectName("chip_service")
        self.chip_service_layout = QtWidgets.QHBoxLayout(self.chip_service)
        self.chip_service_layout.setContentsMargins(8, 4, 8, 4)
        self.chip_service_layout.setSpacing(6)
        self.chip_service_layout.setObjectName("chip_service_layout")
        self.chip_key_service = QtWidgets.QLabel(parent=self.chip_service)
        self.chip_key_service.setObjectName("chip_key_service")
        self.chip_service_layout.addWidget(self.chip_key_service)
        self.service_value = QtWidgets.QLabel(parent=self.chip_service)
        self.service_value.setObjectName("service_value")
        self.chip_service_layout.addWidget(self.service_value)
        self.chips_row.addWidget(self.chip_service)
        self.chip_rx = QtWidgets.QFrame(parent=self.status_strip)
        self.chip_rx.setObjectName("chip_rx")
        self.chip_rx_layout = QtWidgets.QHBoxLayout(self.chip_rx)
        self.chip_rx_layout.setContentsMargins(8, 4, 8, 4)
        self.chip_rx_layout.setSpacing(6)
        self.chip_rx_layout.setObjectName("chip_rx_layout")
        self.chip_key_rx = QtWidgets.QLabel(parent=self.chip_rx)
        self.chip_key_rx.setObjectName("chip_key_rx")
        self.chip_rx_layout.addWidget(self.chip_key_rx)
        self.rx_value = QtWidgets.QLabel(parent=self.chip_rx)
        self.rx_value.setObjectName("rx_value")
        self.chip_rx_layout.addWidget(self.rx_value)
        self.chips_row.addWidget(self.chip_rx)
        self.chip_tx = QtWidgets.QFrame(parent=self.status_strip)
        self.chip_tx.setObjectName("chip_tx")
        self.chip_tx_layout = QtWidgets.QHBoxLayout(self.chip_tx)
        self.chip_tx_layout.setContentsMargins(8, 4, 8, 4)
        self.chip_tx_layout.setSpacing(6)
        self.chip_tx_layout.setObjectName("chip_tx_layout")
        self.chip_key_tx = QtWidgets.QLabel(parent=self.chip_tx)
        self.chip_key_tx.setObjectName("chip_key_tx")
        self.chip_tx_layout.addWidget(self.chip_key_tx)
        self.tx_value = QtWidgets.QLabel(parent=self.chip_tx)
        self.tx_value.setObjectName("tx_value")
        self.chip_tx_layout.addWidget(self.tx_value)
        self.chips_row.addWidget(self.chip_tx)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.chips_row.addItem(spacerItem2)
        self.status_layout.addLayout(self.chips_row)
        self.config_summary = QtWidgets.QLabel(parent=self.status_strip)
        self.config_summary.setText("")
        self.config_summary.setObjectName("config_summary")
        self.status_layout.addWidget(self.config_summary)
        self.ble_root_layout.addWidget(self.status_strip)
        self.body_splitter = QtWidgets.QSplitter(parent=self.ble_tab)
        self.body_splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.body_splitter.setChildrenCollapsible(False)
        self.body_splitter.setObjectName("body_splitter")
        self.list_card = QtWidgets.QFrame(parent=self.body_splitter)
        self.list_card.setObjectName("list_card")
        self.list_layout = QtWidgets.QVBoxLayout(self.list_card)
        self.list_layout.setContentsMargins(12, 10, 12, 10)
        self.list_layout.setSpacing(8)
        self.list_layout.setObjectName("list_layout")
        self.list_title = QtWidgets.QLabel(parent=self.list_card)
        self.list_title.setObjectName("list_title")
        self.list_layout.addWidget(self.list_title)
        self.device_list = QtWidgets.QListWidget(parent=self.list_card)
        self.device_list.setMinimumSize(QtCore.QSize(270, 0))
        self.device_list.setAlternatingRowColors(True)
        self.device_list.setObjectName("device_list")
        self.list_layout.addWidget(self.device_list)
        self.list_hint = QtWidgets.QLabel(parent=self.list_card)
        self.list_hint.setObjectName("list_hint")
        self.list_layout.addWidget(self.list_hint)
        self.io_card = QtWidgets.QFrame(parent=self.body_splitter)
        self.io_card.setObjectName("io_card")
        self.io_layout = QtWidgets.QVBoxLayout(self.io_card)
        self.io_layout.setContentsMargins(12, 10, 12, 10)
        self.io_layout.setSpacing(8)
        self.io_layout.setObjectName("io_layout")
        self.io_title = QtWidgets.QLabel(parent=self.io_card)
        self.io_title.setObjectName("io_title")
        self.io_layout.addWidget(self.io_title)
        self.rx_tx_splitter = QtWidgets.QSplitter(parent=self.io_card)
        self.rx_tx_splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.rx_tx_splitter.setChildrenCollapsible(False)
        self.rx_tx_splitter.setObjectName("rx_tx_splitter")
        self.rx_frame = QtWidgets.QFrame(parent=self.rx_tx_splitter)
        self.rx_frame.setObjectName("rx_frame")
        self.rx_layout = QtWidgets.QVBoxLayout(self.rx_frame)
        self.rx_layout.setContentsMargins(8, 8, 8, 8)
        self.rx_layout.setSpacing(6)
        self.rx_layout.setObjectName("rx_layout")
        self.rx_title = QtWidgets.QLabel(parent=self.rx_frame)
        self.rx_title.setObjectName("rx_title")
        self.rx_layout.addWidget(self.rx_title)
        self.rx_view = QtWidgets.QPlainTextEdit(parent=self.rx_frame)
        self.rx_view.setReadOnly(True)
        self.rx_view.setObjectName("rx_view")
        self.rx_layout.addWidget(self.rx_view)
        self.tx_frame = QtWidgets.QFrame(parent=self.rx_tx_splitter)
        self.tx_frame.setObjectName("tx_frame")
        self.tx_layout = QtWidgets.QVBoxLayout(self.tx_frame)
        self.tx_layout.setContentsMargins(8, 8, 8, 8)
        self.tx_layout.setSpacing(6)
        self.tx_layout.setObjectName("tx_layout")
        self.tx_title = QtWidgets.QLabel(parent=self.tx_frame)
        self.tx_title.setObjectName("tx_title")
        self.tx_layout.addWidget(self.tx_title)
        self.tx_view = QtWidgets.QPlainTextEdit(parent=self.tx_frame)
        self.tx_view.setReadOnly(True)
        self.tx_view.setObjectName("tx_view")
        self.tx_layout.addWidget(self.tx_view)
        self.io_layout.addWidget(self.rx_tx_splitter)
        self.send_row = QtWidgets.QHBoxLayout()
        self.send_row.setSpacing(8)
        self.send_row.setObjectName("send_row")
        self.tx_input = QtWidgets.QLineEdit(parent=self.io_card)
        self.tx_input.setObjectName("tx_input")
        self.send_row.addWidget(self.tx_input)
        self.send_button = QtWidgets.QPushButton(parent=self.io_card)
        self.send_button.setObjectName("send_button")
        self.send_row.addWidget(self.send_button)
        self.clear_button = QtWidgets.QPushButton(parent=self.io_card)
        self.clear_button.setObjectName("clear_button")
        self.send_row.addWidget(self.clear_button)
        self.io_layout.addLayout(self.send_row)
        self.quick_row = QtWidgets.QHBoxLayout()
        self.quick_row.setSpacing(8)
        self.quick_row.setObjectName("quick_row")
        self.quick_cmd_lab = QtWidgets.QLabel(parent=self.io_card)
        self.quick_cmd_lab.setObjectName("quick_cmd_lab")
        self.quick_row.addWidget(self.quick_cmd_lab)
        self.ping_button = QtWidgets.QPushButton(parent=self.io_card)
        self.ping_button.setObjectName("ping_button")
        self.quick_row.addWidget(self.ping_button)
        self.get_status_button = QtWidgets.QPushButton(parent=self.io_card)
        self.get_status_button.setObjectName("get_status_button")
        self.quick_row.addWidget(self.get_status_button)
        self.reboot_button = QtWidgets.QPushButton(parent=self.io_card)
        self.reboot_button.setObjectName("reboot_button")
        self.quick_row.addWidget(self.reboot_button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.quick_row.addItem(spacerItem3)
        self.io_layout.addLayout(self.quick_row)
        self.ble_root_layout.addWidget(self.body_splitter)
        self.tabWidget.addTab(self.ble_tab, "")
        self.steering_tab = QtWidgets.QWidget()
        self.steering_tab.setObjectName("steering_tab")
        self.steering_root_layout = QtWidgets.QVBoxLayout(self.steering_tab)
        self.steering_root_layout.setContentsMargins(12, 12, 12, 12)
        self.steering_root_layout.setSpacing(10)
        self.steering_root_layout.setObjectName("steering_root_layout")
        self.steering_hero_card = QtWidgets.QFrame(parent=self.steering_tab)
        self.steering_hero_card.setObjectName("steering_hero_card")
        self.steering_hero_layout = QtWidgets.QVBoxLayout(self.steering_hero_card)
        self.steering_hero_layout.setContentsMargins(14, 10, 14, 10)
        self.steering_hero_layout.setSpacing(2)
        self.steering_hero_layout.setObjectName("steering_hero_layout")
        self.steering_hero_title_row = QtWidgets.QHBoxLayout()
        self.steering_hero_title_row.setSpacing(8)
        self.steering_hero_title_row.setObjectName("steering_hero_title_row")
        self.steering_hero_title = QtWidgets.QLabel(parent=self.steering_hero_card)
        self.steering_hero_title.setObjectName("steering_hero_title")
        self.steering_hero_title_row.addWidget(self.steering_hero_title)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.steering_hero_title_row.addItem(spacerItem4)
        self.steering_conn_led = QtWidgets.QLabel(parent=self.steering_hero_card)
        self.steering_conn_led.setMinimumSize(QtCore.QSize(24, 24))
        self.steering_conn_led.setMaximumSize(QtCore.QSize(24, 24))
        self.steering_conn_led.setText("")
        self.steering_conn_led.setObjectName("steering_conn_led")
        self.steering_hero_title_row.addWidget(self.steering_conn_led)
        self.steering_hero_layout.addLayout(self.steering_hero_title_row)
        self.steering_hero_subtitle = QtWidgets.QLabel(parent=self.steering_hero_card)
        self.steering_hero_subtitle.setObjectName("steering_hero_subtitle")
        self.steering_hero_layout.addWidget(self.steering_hero_subtitle)
        self.steering_root_layout.addWidget(self.steering_hero_card)
        self.steering_vertical_splitter = QtWidgets.QSplitter(parent=self.steering_tab)
        self.steering_vertical_splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.steering_vertical_splitter.setChildrenCollapsible(False)
        self.steering_vertical_splitter.setObjectName("steering_vertical_splitter")
        self.scope_card = QtWidgets.QFrame(parent=self.steering_vertical_splitter)
        self.scope_card.setObjectName("scope_card")
        self.scope_card_layout = QtWidgets.QVBoxLayout(self.scope_card)
        self.scope_card_layout.setContentsMargins(12, 10, 12, 10)
        self.scope_card_layout.setSpacing(8)
        self.scope_card_layout.setObjectName("scope_card_layout")
        self.scope_header_row = QtWidgets.QHBoxLayout()
        self.scope_header_row.setSpacing(8)
        self.scope_header_row.setObjectName("scope_header_row")
        self.scope_title = QtWidgets.QLabel(parent=self.scope_card)
        self.scope_title.setObjectName("scope_title")
        self.scope_header_row.addWidget(self.scope_title)
        self.scope_hint = QtWidgets.QLabel(parent=self.scope_card)
        self.scope_hint.setObjectName("scope_hint")
        self.scope_header_row.addWidget(self.scope_hint)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.scope_header_row.addItem(spacerItem5)
        self.scope_window_lab = QtWidgets.QLabel(parent=self.scope_card)
        self.scope_window_lab.setObjectName("scope_window_lab")
        self.scope_header_row.addWidget(self.scope_window_lab)
        self.scope_window_combo = QtWidgets.QComboBox(parent=self.scope_card)
        self.scope_window_combo.setObjectName("scope_window_combo")
        self.scope_window_combo.addItem("")
        self.scope_window_combo.addItem("")
        self.scope_window_combo.addItem("")
        self.scope_window_combo.addItem("")
        self.scope_header_row.addWidget(self.scope_window_combo)
        self.scope_pause_button = QtWidgets.QPushButton(parent=self.scope_card)
        self.scope_pause_button.setObjectName("scope_pause_button")
        self.scope_header_row.addWidget(self.scope_pause_button)
        self.scope_clear_button = QtWidgets.QPushButton(parent=self.scope_card)
        self.scope_clear_button.setObjectName("scope_clear_button")
        self.scope_header_row.addWidget(self.scope_clear_button)
        self.scope_live_badge = QtWidgets.QLabel(parent=self.scope_card)
        self.scope_live_badge.setObjectName("scope_live_badge")
        self.scope_header_row.addWidget(self.scope_live_badge)
        self.scope_card_layout.addLayout(self.scope_header_row)
        self.scope_host = QtWidgets.QFrame(parent=self.scope_card)
        self.scope_host.setObjectName("scope_host")
        self.scope_host_layout = QtWidgets.QVBoxLayout(self.scope_host)
        self.scope_host_layout.setContentsMargins(0, 0, 0, 0)
        self.scope_host_layout.setSpacing(0)
        self.scope_host_layout.setObjectName("scope_host_layout")
        self.scope_card_layout.addWidget(self.scope_host)
        self.steering_bottom_splitter = QtWidgets.QSplitter(parent=self.steering_vertical_splitter)
        self.steering_bottom_splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.steering_bottom_splitter.setChildrenCollapsible(False)
        self.steering_bottom_splitter.setObjectName("steering_bottom_splitter")
        self.control_column = QtWidgets.QWidget(parent=self.steering_bottom_splitter)
        self.control_column.setObjectName("control_column")
        self.control_column_layout = QtWidgets.QVBoxLayout(self.control_column)
        self.control_column_layout.setContentsMargins(0, 0, 0, 0)
        self.control_column_layout.setSpacing(10)
        self.control_column_layout.setObjectName("control_column_layout")
        self.pid_card = QtWidgets.QFrame(parent=self.control_column)
        self.pid_card.setObjectName("pid_card")
        self.pid_card_layout = QtWidgets.QVBoxLayout(self.pid_card)
        self.pid_card_layout.setContentsMargins(12, 10, 12, 10)
        self.pid_card_layout.setSpacing(8)
        self.pid_card_layout.setObjectName("pid_card_layout")
        self.pid_title = QtWidgets.QLabel(parent=self.pid_card)
        self.pid_title.setObjectName("pid_title")
        self.pid_card_layout.addWidget(self.pid_title)
        self.pid_grid = QtWidgets.QGridLayout()
        self.pid_grid.setSpacing(8)
        self.pid_grid.setObjectName("pid_grid")
        self.kp_lab = QtWidgets.QLabel(parent=self.pid_card)
        self.kp_lab.setObjectName("kp_lab")
        self.pid_grid.addWidget(self.kp_lab, 0, 0, 1, 1)
        self.kp_spin = QtWidgets.QDoubleSpinBox(parent=self.pid_card)
        self.kp_spin.setDecimals(4)
        self.kp_spin.setMaximum(200.0)
        self.kp_spin.setProperty("value", 0.2)
        self.kp_spin.setObjectName("kp_spin")
        self.pid_grid.addWidget(self.kp_spin, 0, 1, 1, 1)
        self.ki_lab = QtWidgets.QLabel(parent=self.pid_card)
        self.ki_lab.setObjectName("ki_lab")
        self.pid_grid.addWidget(self.ki_lab, 0, 2, 1, 1)
        self.ki_spin = QtWidgets.QDoubleSpinBox(parent=self.pid_card)
        self.ki_spin.setDecimals(4)
        self.ki_spin.setMaximum(200.0)
        self.ki_spin.setProperty("value", 0.08)
        self.ki_spin.setObjectName("ki_spin")
        self.pid_grid.addWidget(self.ki_spin, 0, 3, 1, 1)
        self.kd_lab = QtWidgets.QLabel(parent=self.pid_card)
        self.kd_lab.setObjectName("kd_lab")
        self.pid_grid.addWidget(self.kd_lab, 1, 0, 1, 1)
        self.kd_spin = QtWidgets.QDoubleSpinBox(parent=self.pid_card)
        self.kd_spin.setDecimals(4)
        self.kd_spin.setMaximum(200.0)
        self.kd_spin.setProperty("value", 0.005)
        self.kd_spin.setObjectName("kd_spin")
        self.pid_grid.addWidget(self.kd_spin, 1, 1, 1, 1)
        self.pid_out_limit_lab = QtWidgets.QLabel(parent=self.pid_card)
        self.pid_out_limit_lab.setObjectName("pid_out_limit_lab")
        self.pid_grid.addWidget(self.pid_out_limit_lab, 1, 2, 1, 1)
        self.pid_out_limit_spin = QtWidgets.QDoubleSpinBox(parent=self.pid_card)
        self.pid_out_limit_spin.setDecimals(1)
        self.pid_out_limit_spin.setMaximum(100.0)
        self.pid_out_limit_spin.setProperty("value", 70.0)
        self.pid_out_limit_spin.setObjectName("pid_out_limit_spin")
        self.pid_grid.addWidget(self.pid_out_limit_spin, 1, 3, 1, 1)
        self.pid_card_layout.addLayout(self.pid_grid)
        self.pid_button_row = QtWidgets.QHBoxLayout()
        self.pid_button_row.setSpacing(8)
        self.pid_button_row.setObjectName("pid_button_row")
        self.pid_apply_button = QtWidgets.QPushButton(parent=self.pid_card)
        self.pid_apply_button.setObjectName("pid_apply_button")
        self.pid_button_row.addWidget(self.pid_apply_button)
        self.pid_reset_i_button = QtWidgets.QPushButton(parent=self.pid_card)
        self.pid_reset_i_button.setObjectName("pid_reset_i_button")
        self.pid_button_row.addWidget(self.pid_reset_i_button)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.pid_button_row.addItem(spacerItem6)
        self.pid_card_layout.addLayout(self.pid_button_row)
        self.control_column_layout.addWidget(self.pid_card)
        self.setpoint_card = QtWidgets.QFrame(parent=self.control_column)
        self.setpoint_card.setObjectName("setpoint_card")
        self.setpoint_card_layout = QtWidgets.QVBoxLayout(self.setpoint_card)
        self.setpoint_card_layout.setContentsMargins(12, 10, 12, 10)
        self.setpoint_card_layout.setSpacing(8)
        self.setpoint_card_layout.setObjectName("setpoint_card_layout")
        self.setpoint_title = QtWidgets.QLabel(parent=self.setpoint_card)
        self.setpoint_title.setObjectName("setpoint_title")
        self.setpoint_card_layout.addWidget(self.setpoint_title)
        self.setpoint_body_row = QtWidgets.QHBoxLayout()
        self.setpoint_body_row.setSpacing(10)
        self.setpoint_body_row.setObjectName("setpoint_body_row")
        self.knob_frame = QtWidgets.QFrame(parent=self.setpoint_card)
        self.knob_frame.setObjectName("knob_frame")
        self.knob_frame_layout = QtWidgets.QVBoxLayout(self.knob_frame)
        self.knob_frame_layout.setContentsMargins(10, 10, 10, 10)
        self.knob_frame_layout.setSpacing(6)
        self.knob_frame_layout.setObjectName("knob_frame_layout")
        self.knob_overlay_layout = QtWidgets.QGridLayout()
        self.knob_overlay_layout.setContentsMargins(0, 0, 0, 0)
        self.knob_overlay_layout.setSpacing(0)
        self.knob_overlay_layout.setObjectName("knob_overlay_layout")
        self.angle_knob = QtWidgets.QDial(parent=self.knob_frame)
        self.angle_knob.setMinimumSize(QtCore.QSize(136, 136))
        self.angle_knob.setMaximumSize(QtCore.QSize(136, 136))
        self.angle_knob.setMinimum(0)
        self.angle_knob.setMaximum(330)
        self.angle_knob.setSingleStep(1)
        self.angle_knob.setPageStep(10)
        self.angle_knob.setNotchesVisible(True)
        self.angle_knob.setObjectName("angle_knob")
        self.knob_overlay_layout.addWidget(self.angle_knob, 0, 0, 1, 1)
        self.knob_value_lab = QtWidgets.QLabel(parent=self.knob_frame)
        self.knob_value_lab.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.knob_value_lab.setObjectName("knob_value_lab")
        self.knob_overlay_layout.addWidget(self.knob_value_lab, 0, 0, 1, 1)
        self.knob_frame_layout.addLayout(self.knob_overlay_layout)
        self.setpoint_body_row.addWidget(self.knob_frame)
        self.setpoint_right_layout = QtWidgets.QVBoxLayout()
        self.setpoint_right_layout.setSpacing(8)
        self.setpoint_right_layout.setObjectName("setpoint_right_layout")
        self.setpoint_grid = QtWidgets.QGridLayout()
        self.setpoint_grid.setSpacing(8)
        self.setpoint_grid.setObjectName("setpoint_grid")
        self.angle_set_lab = QtWidgets.QLabel(parent=self.setpoint_card)
        self.angle_set_lab.setObjectName("angle_set_lab")
        self.setpoint_grid.addWidget(self.angle_set_lab, 0, 0, 1, 1)
        self.angle_set_spin = QtWidgets.QDoubleSpinBox(parent=self.setpoint_card)
        self.angle_set_spin.setDecimals(0)
        self.angle_set_spin.setMinimum(0.0)
        self.angle_set_spin.setMaximum(330.0)
        self.angle_set_spin.setSingleStep(1.0)
        self.angle_set_spin.setProperty("value", 0.0)
        self.angle_set_spin.setObjectName("angle_set_spin")
        self.setpoint_grid.addWidget(self.angle_set_spin, 0, 1, 1, 1)
        self.adc_set_lab = QtWidgets.QLabel(parent=self.setpoint_card)
        self.adc_set_lab.setObjectName("adc_set_lab")
        self.setpoint_grid.addWidget(self.adc_set_lab, 1, 0, 1, 1)
        self.adc_set_spin = QtWidgets.QLineEdit(parent=self.setpoint_card)
        self.adc_set_spin.setReadOnly(True)
        self.adc_set_spin.setObjectName("adc_set_spin")
        self.setpoint_grid.addWidget(self.adc_set_spin, 1, 1, 1, 1)
        self.setpoint_right_layout.addLayout(self.setpoint_grid)
        self.setpoint_button_row = QtWidgets.QHBoxLayout()
        self.setpoint_button_row.setSpacing(8)
        self.setpoint_button_row.setObjectName("setpoint_button_row")
        self.setpoint_send_button = QtWidgets.QPushButton(parent=self.setpoint_card)
        self.setpoint_send_button.setObjectName("setpoint_send_button")
        self.setpoint_button_row.addWidget(self.setpoint_send_button)
        self.motor_enable_button = QtWidgets.QPushButton(parent=self.setpoint_card)
        self.motor_enable_button.setObjectName("motor_enable_button")
        self.setpoint_button_row.addWidget(self.motor_enable_button)
        self.motor_stop_button = QtWidgets.QPushButton(parent=self.setpoint_card)
        self.motor_stop_button.setObjectName("motor_stop_button")
        self.setpoint_button_row.addWidget(self.motor_stop_button)
        self.setpoint_right_layout.addLayout(self.setpoint_button_row)
        self.setpoint_hint = QtWidgets.QLabel(parent=self.setpoint_card)
        self.setpoint_hint.setObjectName("setpoint_hint")
        self.setpoint_right_layout.addWidget(self.setpoint_hint)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.setpoint_right_layout.addItem(spacerItem7)
        self.setpoint_body_row.addLayout(self.setpoint_right_layout)
        self.setpoint_card_layout.addLayout(self.setpoint_body_row)
        self.control_column_layout.addWidget(self.setpoint_card)
        self.runtime_card = QtWidgets.QFrame(parent=self.steering_bottom_splitter)
        self.runtime_card.setObjectName("runtime_card")
        self.runtime_card_layout = QtWidgets.QVBoxLayout(self.runtime_card)
        self.runtime_card_layout.setContentsMargins(12, 10, 12, 10)
        self.runtime_card_layout.setSpacing(8)
        self.runtime_card_layout.setObjectName("runtime_card_layout")
        self.runtime_title = QtWidgets.QLabel(parent=self.runtime_card)
        self.runtime_title.setObjectName("runtime_title")
        self.runtime_card_layout.addWidget(self.runtime_title)
        self.runtime_grid = QtWidgets.QGridLayout()
        self.runtime_grid.setHorizontalSpacing(8)
        self.runtime_grid.setVerticalSpacing(6)
        self.runtime_grid.setObjectName("runtime_grid")
        self.rt_conn_lab = QtWidgets.QLabel(parent=self.runtime_card)
        self.rt_conn_lab.setObjectName("rt_conn_lab")
        self.runtime_grid.addWidget(self.rt_conn_lab, 0, 0, 1, 1)
        self.rt_conn_value = QtWidgets.QLabel(parent=self.runtime_card)
        self.rt_conn_value.setObjectName("rt_conn_value")
        self.runtime_grid.addWidget(self.rt_conn_value, 0, 1, 1, 1)
        self.rt_set_lab = QtWidgets.QLabel(parent=self.runtime_card)
        self.rt_set_lab.setObjectName("rt_set_lab")
        self.runtime_grid.addWidget(self.rt_set_lab, 1, 0, 1, 1)
        self.rt_set_value = QtWidgets.QLabel(parent=self.runtime_card)
        self.rt_set_value.setObjectName("rt_set_value")
        self.runtime_grid.addWidget(self.rt_set_value, 1, 1, 1, 1)
        self.rt_fb_lab = QtWidgets.QLabel(parent=self.runtime_card)
        self.rt_fb_lab.setObjectName("rt_fb_lab")
        self.runtime_grid.addWidget(self.rt_fb_lab, 2, 0, 1, 1)
        self.rt_fb_value = QtWidgets.QLabel(parent=self.runtime_card)
        self.rt_fb_value.setObjectName("rt_fb_value")
        self.runtime_grid.addWidget(self.rt_fb_value, 2, 1, 1, 1)
        self.rt_err_lab = QtWidgets.QLabel(parent=self.runtime_card)
        self.rt_err_lab.setObjectName("rt_err_lab")
        self.runtime_grid.addWidget(self.rt_err_lab, 3, 0, 1, 1)
        self.rt_err_value = QtWidgets.QLabel(parent=self.runtime_card)
        self.rt_err_value.setObjectName("rt_err_value")
        self.runtime_grid.addWidget(self.rt_err_value, 3, 1, 1, 1)
        self.rt_pwm_lab = QtWidgets.QLabel(parent=self.runtime_card)
        self.rt_pwm_lab.setObjectName("rt_pwm_lab")
        self.runtime_grid.addWidget(self.rt_pwm_lab, 4, 0, 1, 1)
        self.rt_pwm_value = QtWidgets.QLabel(parent=self.runtime_card)
        self.rt_pwm_value.setObjectName("rt_pwm_value")
        self.runtime_grid.addWidget(self.rt_pwm_value, 4, 1, 1, 1)
        self.rt_rpm_lab = QtWidgets.QLabel(parent=self.runtime_card)
        self.rt_rpm_lab.setObjectName("rt_rpm_lab")
        self.runtime_grid.addWidget(self.rt_rpm_lab, 5, 0, 1, 1)
        self.rt_rpm_value = QtWidgets.QLabel(parent=self.runtime_card)
        self.rt_rpm_value.setObjectName("rt_rpm_value")
        self.runtime_grid.addWidget(self.rt_rpm_value, 5, 1, 1, 1)
        self.rt_vbus_lab = QtWidgets.QLabel(parent=self.runtime_card)
        self.rt_vbus_lab.setObjectName("rt_vbus_lab")
        self.runtime_grid.addWidget(self.rt_vbus_lab, 6, 0, 1, 1)
        self.rt_vbus_value = QtWidgets.QLabel(parent=self.runtime_card)
        self.rt_vbus_value.setObjectName("rt_vbus_value")
        self.runtime_grid.addWidget(self.rt_vbus_value, 6, 1, 1, 1)
        self.runtime_card_layout.addLayout(self.runtime_grid)
        self.runtime_hint = QtWidgets.QLabel(parent=self.runtime_card)
        self.runtime_hint.setObjectName("runtime_hint")
        self.runtime_card_layout.addWidget(self.runtime_hint)
        self.telemetry_raw_title = QtWidgets.QLabel(parent=self.runtime_card)
        self.telemetry_raw_title.setObjectName("telemetry_raw_title")
        self.runtime_card_layout.addWidget(self.telemetry_raw_title)
        self.telemetry_raw_view = QtWidgets.QPlainTextEdit(parent=self.runtime_card)
        self.telemetry_raw_view.setReadOnly(True)
        self.telemetry_raw_view.setObjectName("telemetry_raw_view")
        self.runtime_card_layout.addWidget(self.telemetry_raw_view)
        self.telemetry_cmd_row = QtWidgets.QHBoxLayout()
        self.telemetry_cmd_row.setSpacing(8)
        self.telemetry_cmd_row.setObjectName("telemetry_cmd_row")
        self.telemetry_cmd_edit = QtWidgets.QLineEdit(parent=self.runtime_card)
        self.telemetry_cmd_edit.setObjectName("telemetry_cmd_edit")
        self.telemetry_cmd_row.addWidget(self.telemetry_cmd_edit)
        self.telemetry_send_button = QtWidgets.QPushButton(parent=self.runtime_card)
        self.telemetry_send_button.setObjectName("telemetry_send_button")
        self.telemetry_cmd_row.addWidget(self.telemetry_send_button)
        self.telemetry_clear_button = QtWidgets.QPushButton(parent=self.runtime_card)
        self.telemetry_clear_button.setObjectName("telemetry_clear_button")
        self.telemetry_cmd_row.addWidget(self.telemetry_clear_button)
        self.runtime_card_layout.addLayout(self.telemetry_cmd_row)
        self.steering_root_layout.addWidget(self.steering_vertical_splitter)
        self.tabWidget.addTab(self.steering_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.hero_title.setText(_translate("MainWindow", "BLE DEVICE CONFIG"))
        self.ble_conn_led.setToolTip(_translate("MainWindow", "BLE Link LED"))
        self.hero_subtitle.setText(_translate("MainWindow", "Search, connect, configure UUID, send and receive text"))
        self.section_title.setText(_translate("MainWindow", "DEVICE / CONNECTION"))
        self.device_filter_lab.setText(_translate("MainWindow", "Device Filter"))
        self.device_filter_edit.setPlaceholderText(_translate("MainWindow", "Leave empty to list all devices"))
        self.scan_button.setText(_translate("MainWindow", "SEARCH"))
        self.connect_button.setText(_translate("MainWindow", "CONNECT"))
        self.disconnect_button.setText(_translate("MainWindow", "DISCONNECT"))
        self.apply_config_button.setText(_translate("MainWindow", "APPLY CONFIG"))
        self.service_uuid_lab.setText(_translate("MainWindow", "Service UUID"))
        self.service_uuid_edit.setText(_translate("MainWindow", "0000fff0-0000-1000-8000-00805f9b34fb"))
        self.rx_uuid_lab.setText(_translate("MainWindow", "RX UUID"))
        self.rx_uuid_edit.setText(_translate("MainWindow", "0000fff1-0000-1000-8000-00805f9b34fb"))
        self.tx_uuid_lab.setText(_translate("MainWindow", "TX UUID"))
        self.tx_uuid_edit.setText(_translate("MainWindow", "0000fff2-0000-1000-8000-00805f9b34fb"))
        self.chip_key_state.setText(_translate("MainWindow", "State:"))
        self.conn_value.setText(_translate("MainWindow", "--"))
        self.chip_key_device.setText(_translate("MainWindow", "Device:"))
        self.device_value.setText(_translate("MainWindow", "--"))
        self.chip_key_service.setText(_translate("MainWindow", "Service:"))
        self.service_value.setText(_translate("MainWindow", "--"))
        self.chip_key_rx.setText(_translate("MainWindow", "RX:"))
        self.rx_value.setText(_translate("MainWindow", "--"))
        self.chip_key_tx.setText(_translate("MainWindow", "TX:"))
        self.tx_value.setText(_translate("MainWindow", "--"))
        self.list_title.setText(_translate("MainWindow", "SCAN RESULTS"))
        self.list_hint.setText(_translate("MainWindow", "Tip: select a device then click CONNECT"))
        self.io_title.setText(_translate("MainWindow", "TEXT TX / RX"))
        self.rx_title.setText(_translate("MainWindow", "RECEIVE"))
        self.rx_view.setPlaceholderText(_translate("MainWindow", "Received text will appear here"))
        self.tx_title.setText(_translate("MainWindow", "SEND HISTORY"))
        self.tx_view.setPlaceholderText(_translate("MainWindow", "Sent text history"))
        self.tx_input.setPlaceholderText(_translate("MainWindow", "Input command or text"))
        self.send_button.setText(_translate("MainWindow", "SEND"))
        self.clear_button.setText(_translate("MainWindow", "CLEAR"))
        self.quick_cmd_lab.setText(_translate("MainWindow", "Quick Command"))
        self.ping_button.setText(_translate("MainWindow", "PING"))
        self.get_status_button.setText(_translate("MainWindow", "GET_STATUS"))
        self.reboot_button.setText(_translate("MainWindow", "REBOOT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ble_tab), _translate("MainWindow", "BLE Config"))
        self.steering_hero_title.setText(_translate("MainWindow", "STEERING ENGINE DEBUG CONSOLE"))
        self.steering_conn_led.setToolTip(_translate("MainWindow", "BLE Link LED"))
        self.steering_hero_subtitle.setText(_translate("MainWindow", "DC Motor + Variable Resistor closed-loop tuning and live telemetry"))
        self.scope_title.setText(_translate("MainWindow", "SCOPE WAVEFORM"))
        self.scope_hint.setText(_translate("MainWindow", "Setpoint / Feedback / PWM"))
        self.scope_window_lab.setText(_translate("MainWindow", "Window"))
        self.scope_window_combo.setItemText(0, _translate("MainWindow", "8 s"))
        self.scope_window_combo.setItemText(1, _translate("MainWindow", "12 s"))
        self.scope_window_combo.setItemText(2, _translate("MainWindow", "20 s"))
        self.scope_window_combo.setItemText(3, _translate("MainWindow", "30 s"))
        self.scope_pause_button.setText(_translate("MainWindow", "Pause"))
        self.scope_clear_button.setText(_translate("MainWindow", "Clear"))
        self.scope_live_badge.setText(_translate("MainWindow", "LIVE"))
        self.pid_title.setText(_translate("MainWindow", "PID TUNING"))
        self.kp_lab.setText(_translate("MainWindow", "Kp"))
        self.ki_lab.setText(_translate("MainWindow", "Ki"))
        self.kd_lab.setText(_translate("MainWindow", "Kd"))
        self.pid_out_limit_lab.setText(_translate("MainWindow", "Output Limit"))
        self.pid_apply_button.setText(_translate("MainWindow", "Apply PID"))
        self.pid_reset_i_button.setText(_translate("MainWindow", "Reset Integral"))
        self.setpoint_title.setText(_translate("MainWindow", "STEERING COMMAND"))
        self.knob_value_lab.setText(_translate("MainWindow", "0 deg"))
        self.angle_set_lab.setText(_translate("MainWindow", "Target Angle (deg)"))
        self.adc_set_lab.setText(_translate("MainWindow", "Target ADC (0~4095)"))
        self.adc_set_spin.setText(_translate("MainWindow", "0"))
        self.setpoint_send_button.setText(_translate("MainWindow", "Send Setpoint"))
        self.motor_enable_button.setText(_translate("MainWindow", "Enable Motor"))
        self.motor_stop_button.setText(_translate("MainWindow", "Emergency Stop"))
        self.setpoint_hint.setText(_translate("MainWindow", "Knob range: 0 to 330 deg, step: 1 deg. Use Emergency Stop when needed."))
        self.runtime_title.setText(_translate("MainWindow", "REAL-TIME PARAMETERS"))
        self.rt_conn_lab.setText(_translate("MainWindow", "Connection"))
        self.rt_conn_value.setText(_translate("MainWindow", "Disconnected"))
        self.rt_set_lab.setText(_translate("MainWindow", "Setpoint"))
        self.rt_set_value.setText(_translate("MainWindow", "0.0 "))
        self.rt_fb_lab.setText(_translate("MainWindow", "Feedback"))
        self.rt_fb_value.setText(_translate("MainWindow", "0.0 "))
        self.rt_err_lab.setText(_translate("MainWindow", "Error"))
        self.rt_err_value.setText(_translate("MainWindow", "0.0 deg"))
        self.rt_pwm_lab.setText(_translate("MainWindow", "PWM Output"))
        self.rt_pwm_value.setText(_translate("MainWindow", "0.0 %"))
        self.rt_rpm_lab.setText(_translate("MainWindow", "Motor Speed"))
        self.rt_rpm_value.setText(_translate("MainWindow", "0.0 rpm"))
        self.rt_vbus_lab.setText(_translate("MainWindow", "Bus Voltage"))
        self.rt_vbus_value.setText(_translate("MainWindow", "0.0 V"))
        self.runtime_hint.setText(_translate("MainWindow", "Tip: supports set=12.5, fb=11.9, pwm=28, rpm=320, AT+MOTVR: 2073, AT+MOTPWM: -5"))
        self.telemetry_raw_title.setText(_translate("MainWindow", "RAW TELEMETRY"))
        self.telemetry_raw_view.setPlaceholderText(_translate("MainWindow", "RX/TX log and parsed steering telemetry"))
        self.telemetry_cmd_edit.setPlaceholderText(_translate("MainWindow", "Manual command, e.g. STEER_PID kp=1.3 ki=0.05 kd=0.01"))
        self.telemetry_send_button.setText(_translate("MainWindow", "Send Manual CMD"))
        self.telemetry_clear_button.setText(_translate("MainWindow", "Clear Raw Telemetry"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.steering_tab), _translate("MainWindow", "Steering Debug"))
