#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

/*
PDM
*/
#define PDM_CLK_IO (GPIO_NUM_41)
#define PDM_DATA_IO (GPIO_NUM_42)

/*
I2S
*/
#define I2S_NUM (I2S_NUM_0)
#define I2S_BCK_IO (GPIO_NUM_40)
#define I2S_WS_IO (GPIO_NUM_39)
#define I2S_DO_IO (GPIO_NUM_38)
#define I2S_DI_IO (GPIO_NUM_NC)

/*
    GPBA02B peripheral
*/
#define GPBA02B_SPI_HOST (SPI3_HOST)
#define GPBA02B_IO_MISO (GPIO_NUM_47)
#define GPBA02B_IO_MOSI (GPIO_NUM_48)
#define GPBA02B_IO_CLK (GPIO_NUM_45)
#define GPBA02B_IO_CS (GPIO_NUM_46)
#define GPBA02B_DEFAULT_CLOCK_HZ (8 * 1000 * 1000)
#define GPBA02B_DEVICE_ID (0)
#define GPBA02B_HOST_IRQ_GPIO (GPIO_NUM_NC)

#endif  // _BOARD_CONFIG_H_
